name: Build coop

on:
    workflow_dispatch:
    push:
        branches: [ cici ]

jobs:
    build-macos-arm:
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]') }}
        runs-on: macos-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                brew install make mingw-w64 sdl2 pkg-config glew glfw3 coreutils

            - name: debug
              run: env

            - name: Build the game
              run: |
                gmake OSX_BUILD=1 -j$(sysctl -n hw.ncpu)

            - name: Code sign the app (Ad-Hoc)
              run: |
                codesign --force --deep --sign - ./build/us_pc/sm64coopdx.app

            - name: Generate hash
              run: |
                cd tools
                g++ -std=c++17 -o hash_file hash_file.cpp
                echo "::notice ::$(./hash_file ../build/us_pc/sm64coopdx.app/Contents/MacOS/sm64coopdx)"

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: sm64coopdx-macos-arm
                path: ./build/us_pc/sm64coopdx_macOS_ARM.zip
